// Don't modify, generated using unocommands.py

var unoCommandsArray = {
    ParaspaceIncrease: _('Increase'),
    ParaspaceDecrease: _('Decrease'),
    Italic: _('Italic'),
    Bold: _('Bold'),
    Grow: _('Increase'),
    Shrink: _('Decrease'),
    Shadowed: _('Shadow'),
    OutlineFont: _('Outline'),
    Strikeout: _('Strikethrough'),
    Underline: _('Underline'),
    Overline: _('Overline'),
    SpacePara1: _('Line Spacing: 1'),
    SpacePara15: _('Line Spacing: 1.5'),
    SpacePara2: _('Line Spacing: 2'),
    DefaultBullet: _('Bullets'),
    DefaultNumbering: _('Numbering'),
    ChangeCaseToSentenceCase: _('~Sentence case'),
    ChangeCaseToLower: _('~lowercase'),
    ChangeCaseToUpper: _('~UPPERCASE'),
    ChangeCaseToTitleCase: _('~Capitalize Every Word'),
    ChangeCaseToToggleCase: _('~tOGGLE cASE'),
    ChangeCaseRotateCase: _('Cycle Case (Title Case, UPPERCASE, lowercase)'),
    EditStyle: _('Edit'),
    HideDetail: _('~Hide Details'),
    ShowDetail: _('~Show Details'),
    ParaLeftToRight: _('Left-To-Right'),
    Group: _('~Group...'),
    ParaRightToLeft: _('Right-To-Left'),
    Ungroup: _('~Ungroup...'),
    OpenHyperlinkOnCursor: _('Open Link'),
    ClearOutline: _('~Remove Outline'),
    ObjectForwardOne: _('Forward One'),
    ObjectBackOne: _('Back One'),
    BringToFront: _('~Bring to Front'),
    SendToBack: _('~Send to Back'),
    SuperScript: _('Superscript'),
    SubScript: _('Subscript'),
    SmallCaps: _('Small capitals'),
    Redo: _('~Redo'),
    Undo: _('~Undo'),
    Cut: _('~Cut'),
    Copy: _('Cop~y'),
    Paste: _('~Paste'),
    PasteUnformatted: _('Paste Unformatted Text'),
    SelectAll: _('Select ~All'),
    DecrementIndent: _('Decrease'),
    IncrementIndent: _('Increase'),
    SpellOnline: _('Auto Spellcheck'),
    CommonAlignLeft: _('Left'),
    CommonAlignHorizontalCenter: _('Centered'),
    CommonAlignRight: _('Right'),
    CommonAlignTop: _('Top'),
    CommonAlignBottom: _('Bottom'),
    CommonAlignJustified: _('Justified'),
    DeleteAllNotes: _('Delete All Comments'),
    DeleteAuthor: _('Delete All Comments by This Author'),
    ReplyComment: _('Reply Comment'),
    DeleteComment: _('Delete Comment'),
    ArrangeMenu: _('A~rrange'),
    RotateMenu: _('Rot~ate'),
    AnchorMenu: _('Change Anchor'),
    InsertHardHyphen: _('Non-br~eaking hyphen'),
    InsertSoftHyphen: _('S~oft hyphen'),
    InsertNonBreakingSpace: _('~Non-breaking space'),
    InsertZWSP: _('No-~width optional break'),
    InsertZWNBSP: _('No-width no ~break'),
    InsertLRM: _('~Left-to-right mark'),
    InsertRLM: _('~Right-to-left mark'),
    Copy: _('~Copy'),
    Cut: _('~Cut'),
    Paste: _('~Paste'),
    Undo: _('Undo'),
    SetAnchorAtChar: _('Anchor to Character'),
    InsertEndnote: _('~Endnote'),
    UpdateCurIndex: _('Update Index'),
    RemoveTableOf: _('Delete index'),
    RejectAllTrackedChanges: _('Reject All'),
    AcceptAllTrackedChanges: _('Accept All'),
    NextTrackedChange: _('Next'),
    PreviousTrackedChange: _('Pr~evious'),
    TrackChanges: _('~Record'),
    ShowTrackedChanges: _('~Show'),
    RemoveHyperlink: _('Remove Link'),
    CopyHyperlinkLocation: _('Copy Link Location'),
    InsertColumnBreak: _('Insert Column Break'),
    SetAnchorToPage: _('Anchor To Page'),
    SetAnchorToPara: _('Anchor To Paragraph'),
    SetAnchorToFrame: _('Anchor To Frame'),
    SetAnchorToChar: _('Anchor as Character'),
    InsertFootnote: _('~Footnote'),
    UnderlineDouble: _('Double Underline '),
    SuperScript: _('Superscript'),
    SubScript: _('Subscript'),
    RotateLeft: _('Rotate 90° ~Left'),
    RotateRight: _('Rotate 90° ~Right'),
    ResetAttributes: _('Clear'),
    WrapOff: _('Wrap Off'),
    WrapOn: _('~Page Wrap'),
    WrapThrough: _('~Wrap Through'),
    InsertRowsBefore: _('Insert Rows Above'),
    InsertRows: _('Insert Row'),
    InsertRowsAfter: _('Insert Rows Below'),
    InsertColumnsBefore: _('Insert Columns Left'),
    InsertColumns: _('Insert Column'),
    InsertColumnsAfter: _('Insert Columns Right'),
    DeleteRows: _('Delete Rows'),
    DeleteColumns: _('Delete Columns'),
    DeleteTable: _('Delete Table'),
    MergeCells: _('Merge Cells'),
    EntireRow: _('Select Row'),
    EntireCell: _('Select Cell'),
    EntireColumn: _('Select Column'),
    SelectTable: _('Select Table'),
    DecrementLevel: _('Demote One Level'),
    IncrementLevel: _('Promote One Level'),
    SetOptimalColumnWidth: _('Optimal Column Width'),
    JumpUpThisLevel: _('To Previous Paragraph in Level'),
    JumpDownThisLevel: _('To Next Paragraph in Level'),
    MoveUp: _('Move Up'),
    MoveDown: _('Move Down'),
    InsertNeutralParagraph: _('Insert Unnumbered Entry'),
    IncrementSubLevels: _('Promote One Level With Subpoints'),
    MoveUpSubItems: _('Move Up with Subpoints'),
    MoveDownSubItems: _('Move Down with Subpoints'),
    WrapIdeal: _('~Optimal Page Wrap'),
    WrapThroughTransparent: _('In ~Background'),
    NumberingStart: _('Restart Numbering'),
    WrapLeft: _('Wrap Left'),
    WrapRight: _('Wrap Right'),
    WrapAnchorOnly: _('Wrap First Paragraph'),
    WrapContour: _('Wrap Contour On'),
    ControlCodes: _('Formatting Marks'),
    PasteSpecialMenu: _('Paste ~Special'),
    TableInsertMenu: _('~Insert'),
    TableDeleteMenu: _('~Delete'),
    WrapMenu: _('~Wrap'),
    ArrangeFrameMenu: _('Arrange'),
    ContinueNumbering: _('Continue previous numbering'),
    EditStyle: _('E~dit Style...'),
    ArrangeMenu: _('~Arrange'),
    MergeCells: _('Merge Cells'),
    InsertRows: _('Insert Row'),
    InsertRowsAfter: _('Insert Row Below'),
    InsertRowsBefore: _('Insert Row Above'),
    InsertColumns: _('Insert Column'),
    InsertColumnsAfter: _('Insert Column Right'),
    InsertColumnsBefore: _('Insert Column Left'),
    DeleteRows: _('Delete Row'),
    DeleteColumns: _('Delete Column'),
    SelectTable: _('Select Table'),
    EntireColumn: _('Select Column'),
    EntireRow: _('Select Rows'),
    UnderlineDouble: _('Double Underline '),
    ResetAttributes: _('~Clear Direct Formatting'),
    ArrangeMenu: _('A~rrange'),
    ResetAttributes: _('Clear ~Direct Formatting'),
    DeleteRows: _('Delete Rows'),
    DeleteColumns: _('Delete Columns'),
    UnderlineDouble: _('Underline: Double'),
    InsertColumnBreak: _('Insert ~Column Break'),
    InsertRows: _('Insert ~Rows Above'),
    InsertRowsBefore: _('Insert ~Rows Above'),
    InsertColumns: _('Insert Co~lumns Left'),
    InsertColumnsBefore: _('Insert Co~lumns Left'),
    InsertRowsAfter: _('Insert ~Rows Below'),
    InsertColumnsAfter: _('Insert Co~lumns Right'),
    FormatCellDialog: _('Format ~Cells...'),
    SetOptimalColumnWidth: _('~Optimal Column Width...'),
    MergeCells: _('Merge Cells'),
    RecalcPivotTable: _('~Refresh Pivot Table'),
    SetAnchorToPage: _('Anchor: To P~age'),
};

global.UNO_COMMAND_TEXT = function(string) {
	var text = unoCommandsArray[string.substr(5)];
	text = text.replace('~', '');
	return text;
}
